### PR TITLE
Feature: Added emgr_list module to list ifixes

### PR DESCRIPTION
**Pull request by psyntium**
List interim fixes on the system with proper parsing

from issue https://github.com/IBM/ansible-power-aix/issues/235

Signed-off-by: Syahrul Aiman Shaharuddin <syahrul.aiman@my.ibm.com>

### CODE REVIEW

**Comment by nitismis** [comment]
Hi @psyntium 
The review might take sometime. Meanwhile, Can you post test outputs in the comment ?
This is a new module, so we would like to have a demo playbook as well to understand the module thoroughly.
Thanks !

**Comment by psyntium** [comment]
here's the sample output:
```json
{
        "changed": false,
        "count": 3,
        "failed": false,
        "ifixes": [
            {
                "abstract": "Multithreaded apps core dump / hang",
                "id": "1",
                "install_time": "10/16/22 01:44:18",
                "label": "IJ30808s1a",
                "state": "*Q*",
                "state_desc": "REBOOT REQUIRED",
                "updated_by": ""
            },
            {
                "abstract": "IJ29730 LOAD MODULE AUTH ISSUES",
                "id": "2",
                "install_time": "10/16/22 07:00:01",
                "label": "IJ29730s1b",
                "state": "*Q*",
                "state_desc": "REBOOT REQUIRED",
                "updated_by": ""
            },
            {
                "abstract": "ifix for APAR IJ30108",
                "id": "3",
                "install_time": "10/16/22 07:00:31",
                "label": "IJ30108s1a",
                "state": "S",
                "state_desc": "STABLE",
                "updated_by": ""
            }
        ],
        "msg": "Command 'emgr -l' successful.",
        "stderr": "",
        "stderr_lines": [],
        "stdout": "\nID  STATE LABEL      INSTALL TIME      UPDATED BY ABSTRACT\n=== ===== ========== ================= ========== ======================================\n1   *Q*   IJ30808s1a 10/16/22 01:44:18            Multithreaded apps core dump / hang   \n2   *Q*   IJ29730s1b 10/16/22 07:00:01            IJ29730 LOAD MODULE AUTH ISSUES       \n3    S    IJ30108s1a 10/16/22 07:00:31            ifix for APAR IJ30108                 \n\nSTATE codes:\n S = STABLE\n M = MOUNTED\n U = UNMOUNTED\n Q = REBOOT REQUIRED\n B = BROKEN\n I = INSTALLING\n R = REMOVING\n T = TESTED\n P = PATCHED\n N = NOT PATCHED\n SP = STABLE + PATCHED\n SN = STABLE + NOT PATCHED\n QP = BOOT IMAGE MODIFIED + PATCHED\n QN = BOOT IMAGE MODIFIED + NOT PATCHED\n RQ = REMOVING + REBOOT REQUIRED\n",
        "stdout_lines": [
            "",
            "ID  STATE LABEL      INSTALL TIME      UPDATED BY ABSTRACT",
            "=== ===== ========== ================= ========== ======================================",
            "1   *Q*   IJ30808s1a 10/16/22 01:44:18            Multithreaded apps core dump / hang   ",
            "2   *Q*   IJ29730s1b 10/16/22 07:00:01            IJ29730 LOAD MODULE AUTH ISSUES       ",
            "3    S    IJ30108s1a 10/16/22 07:00:31            ifix for APAR IJ30108                 ",
            "",
            "STATE codes:",
            " S = STABLE",
            " M = MOUNTED",
            " U = UNMOUNTED",
            " Q = REBOOT REQUIRED",
            " B = BROKEN",
            " I = INSTALLING",
            " R = REMOVING",
            " T = TESTED",
            " P = PATCHED",
            " N = NOT PATCHED",
            " SP = STABLE + PATCHED",
            " SN = STABLE + NOT PATCHED",
            " QP = BOOT IMAGE MODIFIED + PATCHED",
            " QN = BOOT IMAGE MODIFIED + NOT PATCHED",
            " RQ = REMOVING + REBOOT REQUIRED"
        ]
}
```

**Comment by psyntium** [comment]
Sample playbook:

```yaml
---
- name: "List interim fix on the system"
  hosts: all
  gather_facts: no
  vars:

  collections:
  - ibm.power_aix

  tasks:

  - name: "List interim fix on the system"
    emgr_list:
    register: output

  - debug: var=output
```

**Comment by nitismis** [comment]
Thanks @psyntium for the response.
I have a question for you:
Is there any specific reason that you are introducing a whole new module for this functionality instead of enhancing the existing emgr.py module ?

**Comment by psyntium** [comment]
hi @nitismis 
no, just thought that it would be simpler. If you think it would be better to be on the same module, let me know. And I'll modify that instead and you can reject this.

**Comment by nitismis** [comment]
Hi @psyntium 
It would be much better to enhance the existing emgr module because it will avoid any kind of confusion for other users and it would be more manageable. So, I would request you to enhance the existing emgr module. I am not closing this PR for now. I will wait for you new PR and then close this one.

**Comment by psyntium** [comment]
Hi @nitismis 

I've created a new PR https://github.com/IBM/ansible-power-aix/pull/238

**Comment by nitismis** [comment]
Tracking this PR through PR #238

**Pull request closed without merging**
