### PR TITLE
quote attribute arguments passed to the mkuser/chuser command when creating or modifying a user

### LINKED ISSUE #151: ibm.power_aix.user  fails to create/modify user with space in gecos
**Describe the bug**
Create or modify user fails if gecos contains spaces

**To Reproduce**
example play

    - name: Create user test1
      ibm.power_aix.user:
        state: present
        name: test1
        attributes:
          gecos: "Test1"

    - name: Create user test2
      ibm.power_aix.user:
        state: present
        name: test2
        attributes:
          gecos: "Test2 User for testing gecos"

**Expected behavior**
both users are created with specified gecos

**Output**

    TASK [Create user test1]
 
 
 
 ********************************************************************************************************************************************************************************************
    task path: /home/user/projects/Ansible/PowerPlay/roles/test/tasks/main.yml:4
    changed: [myhost.mydomain] => {"changed": true, "msg": "Username is created SUCCESSFULLY: test1"}

    TASK [Create user test2] 
 
 
 
 ********************************************************************************************************************************************************************************************
    task path: /home/user/projects/Ansible/PowerPlay/roles/test/tasks/main.yml:11
    fatal: [myhost.mydomain]: FAILED! => {"changed": false, "msg": "Failed to create user: test2", "rc": 22, "stderr": "Usage: mkuser [-R load_module] [-a] \"attr=value\" ... newuser\n", "stderr_lines": ["Usage: mkuser [-R load_module] [-a] \"attr=value\" ... newuser"], "stdout": "", "stdout_lines": []}

    PLAY RECAP 
 
 
 
 **********************************************************************************************************************************************************************************************************
    myhost.mydomain     : ok=2    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

**Environment (please complete the following information):**
cat MANIFEST.json 
{
 "collection_info": {
  "namespace": "ibm",
  "name": "power_aix",
  "version": "1.3.1",
  "authors": [
   "Paul B. Finley (@pbfinley1911)"
  ],

ansible 2.9.25
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/de50870/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.9.6 (default, Jul 16 2021, 00:00:00) [GCC 11.1.1 20210531 (Red Hat 11.1.1-3)]

### PR DESCRIPTION
**Pull request by stephenulmer**
Added quoted quotes so the command that is actually run winds up having quotes around the attributes values.

### CODE REVIEW

**Comment by stephenulmer** [comment]
The checks fail in my repo because dev-collection already had merged failing checks... I'm not sure how to deal with that for a PR. This will close #151.

**Comment by stephenulmer** [comment]
Hmmm... okay, some of the failing checks are mine. I'm not sure if the tests are reasonable and I'm also not sure how to run them myself. Can someone point me at the best way to fix-up my dev environment to run the tests locally, or run the same tests in my forked repo?  Thanks.

**Comment by jdejoya17** [comment]
Hi @stephenulmer,

Thank you for being active on our collection.
Here is a readme file on the `tests` directory of this collection
https://github.com/IBM/ansible-power-aix/blob/dev-collection/tests/README.md

This readme file contains various information regarding how to run the tests locally
when developing the collection.

I suggest that you use a virtual environment using python3's venv module.
Instructions on how to create a virtual environment should be including in the
file. (I suggest this as to not clutter your workstation with python modules which
you may need to download for running the tests).

The readme file has multiple sections giving instructions on how to run
specific tests.

If you have any questions regarding this, please do not hesitate to @ me.

- Joseph

**Comment by JLRebello** [comment]
Hi Stephen, I'm looking into this PR, and what's going on with the tests/failures.

**Comment by JLRebello** [comment]
Hi @stephenulmer , we've merged some changes into IBM's repo that should resolve the issues you are having. Please rebase this branch so those changes can be taken into account. Thanks!

**Comment by stephenulmer** [comment]
My apologies that I didn't get back to this in time! I appreciate you doing the work to merge it anyway. I'll catch up and have other updates next week.

**Pull request merged**
