### PR TITLE
Updates from Client work

### PR DESCRIPTION
**Pull request by Rich-J-AIX**
Changes:
* Target didk without PVID accepted
* Divide Used PVs by number of PVs to overcome multiple PVs in rootvg
* Allow install of AIX level lower than NIM master AIX level
* Reduce debug info after checking client OS level
* Add cache VG and Bundle to nimadm options
* Re-order nimadm flags and "quote" disk variable to allow multiple PVs in rootvg
* Correct {{ nim_client_v }} to {{ nim_client }}

Sample of role in playbook.
```
    - include_role:
        name: power_aix/nim_alt_disk_migration
      vars:
        nim_client:      "{{ NIM_Client }}"
        target_disk:
          disk_name:     "{{ Target_DISK.disk_name }}"
          force:         "{{ NIMADM_Force }}"
        lpp_source:      "{{ Target_LPPS }}"
        spot:            "{{ Target_SPOT }}"
        nim_mast_lpp:    "{{ NIM_Mast_LPP }}"
        nimadm_cache_vg: "{{ NIMADM_VG | default('N/A') }}"
        nimadm_bundle:   "{{ Target_eFix | default('N/A') }}"
        control_phases:
          validate_nim_resources: "{{ NIM_Res_Check }}"
          perform_migration:      "{{ NIM_Migration }}"
        debug_skip_nimadm:        "{{ Skip_nimadm }}"

```

### CODE REVIEW

**Comment by nitismis** [comment]
Hi Rich !
We are reviewing this PR. Can you please paste some playbook outputs (using -vvv) in comment for your changes ?

**Comment by nitismis** [comment]
We are getting some linting issues:
WARNING  Listing 3 violation(s) that are fatal
roles/nim_alt_disk_migration/tasks/main.yml:187: yaml too many spaces after colon (colons)
roles/nim_alt_disk_migration/tasks/main.yml:223: yaml missing starting space in comment (comments)
roles/nim_alt_disk_migration/tasks/main.yml:224: yaml missing starting space in comment (comments)
Error: yaml too many spaces after colon
You can skip specific rules or tags by adding them to your configuration file:
Warning: yaml missing starting space in comment
Warning: yaml missing starting space in comment

Can you please fix these ?

**Comment by nitismis** [comment]
There is also DCO (sign-off) issue. You can commit using -s flag to avoid this:
git commit -s -m 'This is my commit message'
Refer: https://github.com/apps/dco
We are planning to merge this PR in couple of days.

**Comment by Rich-J-AIX** [comment]
Applied updates for lint errors

**Review by nitismis — APPROVED** [review]

**Pull request merged**
