### PR TITLE
Added install_all_updates module for issue #203

### PR DESCRIPTION
**Pull request by syahrul-aiman**
Added `install_all_updates` module for issue #203

`install_all_updates` are modified from `installp` module

### CODE REVIEW

**Comment by syahrul-aiman** [comment]
I have no idea how to resolve the test error. I didn't do any updates on mount module.

**Comment by syahrul-aiman** [comment]
Hi @nitismis 

Do you mind to help and explain why the test case is failing for me?

**Comment by nitismis** [comment]
Hi @syahrul-aiman ,
It is failing for us also. We need to update the testcases for mount module. We are aware of that. It's not because of your PR. Give us sometime, we will review this PR.
Thanks.

**Comment by syahrul-aiman** [comment]
> Hi @syahrul-aiman , It is failing for us also. We need to update the testcases for mount module. We are aware of that. It's not because of your PR. Give us sometime, we will review this PR. Thanks.

Ah OK. Thanks for the quick reply @nitismis. I was wondering if I had done anything wrong.

**Review by nitismis — APPROVED** [review]

**Pull request merged**
