### PR TITLE
Change behaviour of user handling

### PR DESCRIPTION
**Pull request by OliverGeiss**
Desired user handling if state=present:
1) User NOT exists: run module create_user
2) User exists: run module modify_user

Reason: if a user already exists but only an attribute should be changed, it should be possible

### CODE REVIEW

**Comment by nitismis** [comment]
For the modification of any existing user we have provided separate "state" choice, i.e. state==modify.
These changes will be redundant for this use case and the code will start breaking for other usecases.
Please use state==modify in case you want to change the attributes of any existing user.

**Comment by aklyachkin** [comment]
@nitismis I agree with @OliverGeiss. The module is not idempotent if we can't use state: present to amend the user. Many modules work this way even in ibm.power_aix collection. Take a look at lvg, lvol or filesystem modules. They all modifies the objects if they exist and the state is present.
 
The change will not be redundant and will not break anything, because it doesn't introduce anything new. It updates behaviour of "state: present" according to Ansible philosophy.

**Comment by nitismis** [comment]
I have reopened the PR. Will look into this.

**Comment by nitismis** [comment]
If we are going to do this way, only this change will not work and it will require other changes including "modify" code block and documentation. Will you be able to make those changes ? or shall I work on that separately ?

**Comment by aklyachkin** [comment]
Thank you @nitismis! I will try it on my AIX box and if I can I'll do a new pull request.

**Comment by aklyachkin** [comment]
As a first draft, not really pull request. For review and to understand if I am on the right way and do what you mean. 

```diff
*** user.py.orig        Thu Aug 31 16:12:55 2023
--- user.py     Thu Aug 31 16:13:22 2023
***************
*** 180,185 ****
--- 180,240 ----
      return cmd
  
  
+ def parse_lsuserf_output(stdout):
+     '''
+     parse_lsuserf_output returns a dict with all values parsed from
+     lsuser -f output.
+ 
+     argument:
+         stdout:  List of lines. Output from lsuser -f.
+     return:
+         (dict):  Attributes in python dict.
+     '''
+     attrs = dict()
+     for line in stdout.splitlines():
+         if '=' in line:
+             attr, value = line.split('=')
+             attr = attr.strip()
+             value = value.strip()
+             if value != "":
+                 attrs[attr] = value
+     return attrs
+ 
+ 
+ def get_user_attrs(module):
+     '''
+     get_user_attrs returns a dict with all attributes defined for the user.
+     The user must exist. The function will not check its existence.
+ 
+     argument:
+         module  (dict): The Ansible module
+     return:
+         (dict): User attributes
+     '''
+     cmd = "lsuser -f %s" % module.params['name']
+     rc, stdout, stderr = module.run_command(cmd)
+     if rc != 0:
+         return dict()
+     return parse_lsuserf_output(stdout)
+ 
+ 
+ def changed_attrs(module, current):
+     '''
+     changed_attrs checks the difference between current attributes of
+     a user and the attributes set in the module.
+     Dictionary with changed values is returned.
+ 
+     argument:
+         module  (dict): The Ansible module
+         current (dict): Current user attributes
+     return:
+         (dict): Changed user attributes
+     '''
+     newattrs = module.params['attributes']
+     changed = {k: newattrs[k] for k in newattrs if k in current and str(newattrs[k]) != current[k]}
+     return changed
+ 
+ 
  def modify_user(module):
      '''
      Modify_user function modifies the attributes of the user and returns
***************
*** 195,200 ****
--- 250,261 ----
  
      msg = None
      changed = False
+     # Get current user attributes
+     current_attrs = get_user_attrs(module)
+     # Get user attributes to change
+     attrs = changed_attrs(module, current_attrs)
+     # Redefine attributes
+     module.params['attributes'] = attrs
      # Get + Run chuser commands
      cmd = get_chuser_command(module)
      if cmd is not None:
***************
*** 377,382 ****
--- 438,447 ----
              changed = True
          else:
              msg = "User %s already exists." % module.params['name']
+             if module.params['attributes'] is None and module.params['password'] is None:
+                 msg = "Please provide the attributes to be changed for the user: %s" % module.params['name']
+             else:
+                 msg, changed = modify_user(module)
      elif module.params['state'] == 'modify':
          if module.params['attributes'] is None and module.params['password'] is None:
              msg = "Please provide the attributes to be changed for the user: %s" % module.params['name']
```

**Comment by nitismis** [comment]
@aklyachkin 
Sorry for replying late on this. Was stuck in some priority work.
Yes this is exactly what I meant. The code changes which you have suggested looks good to me. Can you also remove all the sections of code which are dealing with action == modify ?

Thanks,

**Comment by aklyachkin** [comment]
@nitismis I created a new pull request with the code - https://github.com/IBM/ansible-power-aix/pull/337

**Comment by nitismis** [comment]
We have handled this through PR #337.
Thanks everyone. Closing the PR as #337 is already merged.

**Pull request closed without merging**
