### PR TITLE
Enhancement to handle mirrored rootvg in case of alt_disk_copy

### PR DESCRIPTION
**Pull request by schamola**
Fix for issue #354

### CODE REVIEW

**Comment by nitismis** [comment]
@neikei , Can you please confirm this is working fine in your environment ?

**Comment by neikei** [comment]
@nitismis, many thanks for the development! Our test in the mirrored environment worked. 🚀 

```bash
# Copy with policy minimize
  - name: Perform an alternate disk copy of the rootvg to the smallest disk that can be selected
    ibm.power_aix.alt_disk:
      action: copy
      disk_size_policy: minimize

# Minimize found the correct disks and created a mirrored copy
    root 27590924 28311888   0 07:14:57  pts/2  0:00 /usr/bin/ksh /usr/sbin/alt_disk_copy -d hdisk4 hdisk14 -B

# Copy with policy nearest
  - name: Perform an alternate disk copy of the rootvg to the smallest disk that can be selected
    ibm.power_aix.alt_disk:
      action: copy
      disk_size_policy: nearest

# Nearest found the correct disks and created a mirrored copy
    root 27001182 20185398   7 07:34:11  pts/2  0:00 /usr/bin/ksh /usr/sbin/alt_disk_copy -d hdisk4 hdisk14 -B
```

The bootlist also looks good, so the "-B" is handled as expected. 👍 

```bash
# Same as nearest but with bootlist
  - name: Perform an alternate disk copy of the rootvg to the smallest disk that can be selected
    ibm.power_aix.alt_disk:
      action: copy
      disk_size_policy: nearest
      bootlist: true

# Focused on bootlist and the "-B" flag is removed as expected
    root 25952718 15073726   0 07:39:03  pts/2  0:00 /usr/bin/ksh /usr/sbin/alt_disk_copy -d hdisk4 hdisk14
```

**Review by neikei — APPROVED** [review]
Code tested successfully.

**Comment by schamola** [comment]
Thanks for letting us know ! @neikei

**Comment by schamola** [comment]
@neikei 
Thanks for letting us know !
We will merge the code and make the new release available soon.

**Review by nitismis — APPROVED** [review]

**Pull request merged**
